//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micway.Models
{   
    using System;    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
        
    public partial class Driver
    {
        [Key]        
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [Required]       
        [DataType(DataType.Date)]//, ErrorMessage = "Invalid Date Value")]        
        public DateTime Dob { get; set; }

        [Required]
        [StringLength(100)]
        [EmailAddress()]
        public string Email { get; set; }
        
        [NotMapped]
        [IgnoreDataMember]
        public string FullName { get; set; }
    }
}
